<a href="https://colab.research.google.com/github/vunnampragathi/projects/blob/main/final_proposal.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:

import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

In [2]:
data = pd.read_csv("/content/LAcity.org_Website_Traffic_-_Page_Views.csv")

In [3]:
data

,date,pageTitle,pageviews
0,01/01/2016 12:00:00 AM,Home | City of Los Angeles,2431
1,01/01/2016 12:00:00 AM,For Job Seekers | City of Los Angeles,634
2,01/01/2016 12:00:00 AM,Latest City Job Opportunities | City of Los An...,522
3,01/01/2016 12:00:00 AM,311 Directory Online Services | City of Los An...,433
4,01/01/2016 12:00:00 AM,Search | City of Los Angeles,414
...,...,...,...
33345,08/26/2019 12:00:00 AM,Tips for Visitors | City of Los Angeles,185
33346,08/26/2019 12:00:00 AM,Los Angeles Municipal Code (LAMC) 85.02 – Vehi...,172
33347,08/26/2019 12:00:00 AM,Planning and Zoning | City of Los Angeles,154
33348,08/26/2019 12:00:00 AM,Council and Committee Meetings | City of Los A...,151
33349,08/26/2019 12:00:00 AM,Housing Services | City of Los Angeles,147

In [4]:
data.shape

(33350, 3)

In [5]:
data.info

<bound method DataFrame.info of                          date  \
0      01/01/2016 12:00:00 AM
1      01/01/2016 12:00:00 AM
2      01/01/2016 12:00:00 AM
3      01/01/2016 12:00:00 AM
4      01/01/2016 12:00:00 AM
...                       ...
33345  08/26/2019 12:00:00 AM
33346  08/26/2019 12:00:00 AM
33347  08/26/2019 12:00:00 AM
33348  08/26/2019 12:00:00 AM
33349  08/26/2019 12:00:00 AM

                                               pageTitle  pageviews
0                             Home | City of Los Angeles       2431
1                  For Job Seekers | City of Los Angeles        634
2      Latest City Job Opportunities | City of Los An...        522
3      311 Directory Online Services | City of Los An...        433
4                           Search | City of Los Angeles        414
...                                                  ...        ...
33345            Tips for Visitors | City of Los Angeles        185
33346  Los Angeles Municipal Code (LAMC) 85.02 – Vehi...        172
33347          Planning and Zoning | City of Los Angeles        154
33348  Council and Committee Meetings | City of Los A...        151
33349             Housing Services | City of Los Angeles        147

[33350 rows x 3 columns]>

In [6]:
data.dtypes

date         object
pageTitle    object
pageviews     int64
dtype: object

In [7]:
df=data.dropna()

In [8]:
df.shape

(33350, 3)

In [9]:
df['date'] = pd.to_datetime(df['date']).dt.date
df['time'] = pd.to_datetime(df['date']).dt.time
print("Date-time-hour-minutes :\n", df)

Date-time-hour-minutes :
              date                                          pageTitle  \
0      2016-01-01                         Home | City of Los Angeles
1      2016-01-01              For Job Seekers | City of Los Angeles
2      2016-01-01  Latest City Job Opportunities | City of Los An...
3      2016-01-01  311 Directory Online Services | City of Los An...
4      2016-01-01                       Search | City of Los Angeles
...           ...                                                ...
33345  2019-08-26            Tips for Visitors | City of Los Angeles
33346  2019-08-26  Los Angeles Municipal Code (LAMC) 85.02 – Vehi...
33347  2019-08-26          Planning and Zoning | City of Los Angeles
33348  2019-08-26  Council and Committee Meetings | City of Los A...
33349  2019-08-26             Housing Services | City of Los Angeles

       pageviews      time
0           2431  00:00:00
1            634  00:00:00
2            522  00:00:00
3            433  00:00:00
4            414  00:00:00
...          ...       ...
33345        185  00:00:00
33346        172  00:00:00
33347        154  00:00:00
33348        151  00:00:00
33349        147  00:00:00

[33350 rows x 4 columns]

In [10]:
df

,date,pageTitle,pageviews,time
0,2016-01-01,Home | City of Los Angeles,2431,00:00:00
1,2016-01-01,For Job Seekers | City of Los Angeles,634,00:00:00
2,2016-01-01,Latest City Job Opportunities | City of Los An...,522,00:00:00
3,2016-01-01,311 Directory Online Services | City of Los An...,433,00:00:00
4,2016-01-01,Search | City of Los Angeles,414,00:00:00
...,...,...,...,...
33345,2019-08-26,Tips for Visitors | City of Los Angeles,185,00:00:00
33346,2019-08-26,Los Angeles Municipal Code (LAMC) 85.02 – Vehi...,172,00:00:00
33347,2019-08-26,Planning and Zoning | City of Los Angeles,154,00:00:00
33348,2019-08-26,Council and Committee Meetings | City of Los A...,151,00:00:00
33349,2019-08-26,Housing Services | City of Los Angeles,147,00:00:00

In [11]:
df['Date'] = pd.to_datetime(df.date, format='%Y-%m-%d')

In [12]:
df['Date'] = df['Date'].dt.strftime('%Y-%m-%d')

In [17]:
df[["year", "month", "day"]] = df["Date"].str.split("-", expand = True)
print("\nNew DataFrame:")
print(df)

New DataFrame:
             date                                          pageTitle  \
0      2016-01-01                         Home | City of Los Angeles
1      2016-01-01              For Job Seekers | City of Los Angeles
2      2016-01-01  Latest City Job Opportunities | City of Los An...
3      2016-01-01  311 Directory Online Services | City of Los An...
4      2016-01-01                       Search | City of Los Angeles
...           ...                                                ...
33345  2019-08-26            Tips for Visitors | City of Los Angeles
33346  2019-08-26  Los Angeles Municipal Code (LAMC) 85.02 – Vehi...
33347  2019-08-26          Planning and Zoning | City of Los Angeles
33348  2019-08-26  Council and Committee Meetings | City of Los A...
33349  2019-08-26             Housing Services | City of Los Angeles

       pageviews      time        Date day month  year
0           2431  00:00:00  2016-01-01  01    01  2016
1            634  00:00:00  2016-01-01  01    01  2016
2            522  00:00:00  2016-01-01  01    01  2016
3            433  00:00:00  2016-01-01  01    01  2016
4            414  00:00:00  2016-01-01  01    01  2016
...          ...       ...         ...  ..   ...   ...
33345        185  00:00:00  2019-08-26  26    08  2019
33346        172  00:00:00  2019-08-26  26    08  2019
33347        154  00:00:00  2019-08-26  26    08  2019
33348        151  00:00:00  2019-08-26  26    08  2019
33349        147  00:00:00  2019-08-26  26    08  2019

[33350 rows x 8 columns]

In [18]:
df

,date,pageTitle,pageviews,time,Date,day,month,year
0,2016-01-01,Home | City of Los Angeles,2431,00:00:00,2016-01-01,01,01,2016
1,2016-01-01,For Job Seekers | City of Los Angeles,634,00:00:00,2016-01-01,01,01,2016
2,2016-01-01,Latest City Job Opportunities | City of Los An...,522,00:00:00,2016-01-01,01,01,2016
3,2016-01-01,311 Directory Online Services | City of Los An...,433,00:00:00,2016-01-01,01,01,2016
4,2016-01-01,Search | City of Los Angeles,414,00:00:00,2016-01-01,01,01,2016
...,...,...,...,...,...,...,...,...
33345,2019-08-26,Tips for Visitors | City of Los Angeles,185,00:00:00,2019-08-26,26,08,2019
33346,2019-08-26,Los Angeles Municipal Code (LAMC) 85.02 – Vehi...,172,00:00:00,2019-08-26,26,08,2019
33347,2019-08-26,Planning and Zoning | City of Los Angeles,154,00:00:00,2019-08-26,26,08,2019
33348,2019-08-26,Council and Committee Meetings | City of Los A...,151,00:00:00,2019-08-26,26,08,2019
33349,2019-08-26,Housing Services | City of Los Angeles,147,00:00:00,2019-08-26,26,08,2019

In [19]:
df.nlargest(15,['pageviews'])

,date,pageTitle,pageviews,time,Date,day,month,year
17630,2017-12-06,Fire Evacuation Information | City of Los Angeles,66429,00:00:00,2017-12-06,06,12,2017
17655,2017-12-07,Fire Evacuation Information | City of Los Angeles,50906,00:00:00,2017-12-07,07,12,2017
17631,2017-12-06,Creek Fire Emergency Updates & Information | C...,40990,00:00:00,2017-12-06,06,12,2017
17632,2017-12-06,City of Los Angeles |,36209,00:00:00,2017-12-06,06,12,2017
17656,2017-12-07,City of Los Angeles |,26976,00:00:00,2017-12-07,07,12,2017
17633,2017-12-06,Skirball Fire Emergency Updates & Information ...,21094,00:00:00,2017-12-06,06,12,2017
17680,2017-12-08,Fire Evacuation Information | City of Los Angeles,16188,00:00:00,2017-12-08,08,12,2017
17681,2017-12-08,City of Los Angeles |,15053,00:00:00,2017-12-08,08,12,2017
27475,2019-01-03,Download the ShakeAlertLA Earthquake Early War...,13387,00:00:00,2019-01-03,03,01,2019
1500,2016-03-01,Page Not Found | City of Los Angeles,11783,00:00:00,2016-03-01,01,03,2016
3100,2016-05-04,City of Los Angeles,11453,00:00:00,2016-05-04,04,05,2016
1525,2016-03-02,Page Not Found | City of Los Angeles,10874,00:00:00,2016-03-02,02,03,2016
17605,2017-12-05,Creek Fire Emergency Updates & Information | C...,9993,00:00:00,2017-12-05,05,12,2017
17634,2017-12-06,Skirball Fire Evacuation Area and Resources | ...,9755,00:00:00,2017-12-06,06,12,2017
10600,2017-02-28,City of Los Angeles,9610,00:00:00,2017-02-28,28,02,2017

ref:https://www.tutorialspoint.com/write-a-program-to-separate-date-and-time-from-the-datetime-column-in-python-pandas

https://stackoverflow.com/questions/33365055/attributeerror-can-only-use-dt-accessor-with-datetimelike-values

https://cmdlinetips.com/2019/03/how-to-select-top-n-rows-with-the-largest-values-in-a-columns-in-pandas/

In [29]:
df1=df.loc[df['year'] =="2016"]
df1

,date,pageTitle,pageviews,time,Date,day,month,year
0,2016-01-01,Home | City of Los Angeles,2431,00:00:00,2016-01-01,01,01,2016
1,2016-01-01,For Job Seekers | City of Los Angeles,634,00:00:00,2016-01-01,01,01,2016
2,2016-01-01,Latest City Job Opportunities | City of Los An...,522,00:00:00,2016-01-01,01,01,2016
3,2016-01-01,311 Directory Online Services | City of Los An...,433,00:00:00,2016-01-01,01,01,2016
4,2016-01-01,Search | City of Los Angeles,414,00:00:00,2016-01-01,01,01,2016
...,...,...,...,...,...,...,...,...
9145,2016-12-31,Utilities | City of Los Angeles,55,00:00:00,2016-12-31,31,12,2016
9146,2016-12-31,City Council | City of Los Angeles,47,00:00:00,2016-12-31,31,12,2016
9147,2016-12-31,Mayor Announces Record Job Growth | City of Lo...,41,00:00:00,2016-12-31,31,12,2016
9148,2016-12-31,City Calendar | City of Los Angeles,38,00:00:00,2016-12-31,31,12,2016
9149,2016-12-31,Departments & Bureaus | City of Los Angeles,35,00:00:00,2016-12-31,31,12,2016

In [30]:
df1.nlargest(15,['pageviews'])

,date,pageTitle,pageviews,time,Date,day,month,year
1500,2016-03-01,Page Not Found | City of Los Angeles,11783,00:00:00,2016-03-01,01,03,2016
3100,2016-05-04,City of Los Angeles,11453,00:00:00,2016-05-04,04,05,2016
1525,2016-03-02,Page Not Found | City of Los Angeles,10874,00:00:00,2016-03-02,02,03,2016
750,2016-01-31,Power Outage Information | City of Los Angeles,9032,00:00:00,2016-01-31,31,01,2016
1475,2016-02-29,Download the New GoLA App | City of Los Angeles,8641,00:00:00,2016-02-29,29,02,2016
1476,2016-02-29,Page Not Found | City of Los Angeles,8637,00:00:00,2016-02-29,29,02,2016
1501,2016-03-01,Download the New GoLA App | City of Los Angeles,7942,00:00:00,2016-03-01,01,03,2016
2900,2016-04-26,Home | City of Los Angeles,7780,00:00:00,2016-04-26,26,04,2016
3125,2016-05-05,City of Los Angeles,7694,00:00:00,2016-05-05,05,05,2016
1526,2016-03-02,Download the New GoLA App | City of Los Angeles,7661,00:00:00,2016-03-02,02,03,2016
2925,2016-04-27,Home | City of Los Angeles,7583,00:00:00,2016-04-27,27,04,2016
2550,2016-04-12,Home | City of Los Angeles,7542,00:00:00,2016-04-12,12,04,2016
2725,2016-04-19,Home | City of Los Angeles,7248,00:00:00,2016-04-19,19,04,2016
3050,2016-05-02,Home | City of Los Angeles,7208,00:00:00,2016-05-02,02,05,2016
2750,2016-04-20,Home | City of Los Angeles,7144,00:00:00,2016-04-20,20,04,2016

In [31]:
df2=df.loc[df['year'] =="2017"]
df2

,date,pageTitle,pageviews,time,Date,day,month,year
9150,2017-01-01,City of Los Angeles,3282,00:00:00,2017-01-01,01,01,2017
9151,2017-01-01,Sanitation & Recycling | City of Los Angeles,1945,00:00:00,2017-01-01,01,01,2017
9152,2017-01-01,Search | City of Los Angeles,920,00:00:00,2017-01-01,01,01,2017
9153,2017-01-01,Find Jobs | City of Los Angeles,753,00:00:00,2017-01-01,01,01,2017
9154,2017-01-01,For Residents | City of Los Angeles,749,00:00:00,2017-01-01,01,01,2017
...,...,...,...,...,...,...,...,...
18275,2017-12-31,Transportation & Parking | City of Los Angeles,49,00:00:00,2017-12-31,31,12,2017
18276,2017-12-31,City Council & Committee Meetings | City of Lo...,44,00:00:00,2017-12-31,31,12,2017
18277,2017-12-31,City Calendar | City of Los Angeles,42,00:00:00,2017-12-31,31,12,2017
18278,2017-12-31,Animal Services | City of Los Angeles,40,00:00:00,2017-12-31,31,12,2017
18279,2017-12-31,Utilities | City of Los Angeles,37,00:00:00,2017-12-31,31,12,2017

In [33]:
df2.nlargest(15,['pageviews'])

,date,pageTitle,pageviews,time,Date,day,month,year
17630,2017-12-06,Fire Evacuation Information | City of Los Angeles,66429,00:00:00,2017-12-06,06,12,2017
17655,2017-12-07,Fire Evacuation Information | City of Los Angeles,50906,00:00:00,2017-12-07,07,12,2017
17631,2017-12-06,Creek Fire Emergency Updates & Information | C...,40990,00:00:00,2017-12-06,06,12,2017
17632,2017-12-06,City of Los Angeles |,36209,00:00:00,2017-12-06,06,12,2017
17656,2017-12-07,City of Los Angeles |,26976,00:00:00,2017-12-07,07,12,2017
17633,2017-12-06,Skirball Fire Emergency Updates & Information ...,21094,00:00:00,2017-12-06,06,12,2017
17680,2017-12-08,Fire Evacuation Information | City of Los Angeles,16188,00:00:00,2017-12-08,08,12,2017
17681,2017-12-08,City of Los Angeles |,15053,00:00:00,2017-12-08,08,12,2017
17605,2017-12-05,Creek Fire Emergency Updates & Information | C...,9993,00:00:00,2017-12-05,05,12,2017
17634,2017-12-06,Skirball Fire Evacuation Area and Resources | ...,9755,00:00:00,2017-12-06,06,12,2017
10600,2017-02-28,City of Los Angeles,9610,00:00:00,2017-02-28,28,02,2017
10575,2017-02-27,City of Los Angeles,9175,00:00:00,2017-02-27,27,02,2017
17606,2017-12-05,City of Los Angeles |,8687,00:00:00,2017-12-05,05,12,2017
16005,2017-10-02,City of Los Angeles |,8579,00:00:00,2017-10-02,02,10,2017
12175,2017-05-02,City of Los Angeles,8133,00:00:00,2017-05-02,02,05,2017

In [34]:
df3=df.loc[df['year'] =="2018"]
df3

,date,pageTitle,pageviews,time,Date,day,month,year
18280,2018-01-01,City of Los Angeles |,2982,00:00:00,2018-01-01,01,01,2018
18281,2018-01-01,Find Jobs | City of Los Angeles,1119,00:00:00,2018-01-01,01,01,2018
18282,2018-01-01,Search | City of Los Angeles,529,00:00:00,2018-01-01,01,01,2018
18283,2018-01-01,Bulky Item Collection/Disposal | City of Los A...,433,00:00:00,2018-01-01,01,01,2018
18284,2018-01-01,For Residents | City of Los Angeles,367,00:00:00,2018-01-01,01,01,2018
...,...,...,...,...,...,...,...,...
27420,2018-12-31,City Calendar | City of Los Angeles,80,00:00:00,2018-12-31,31,12,2018
27421,2018-12-31,"City Charter, Rules, and Codes | City of Los A...",69,00:00:00,2018-12-31,31,12,2018
27422,2018-12-31,Watch the Countdown to 2017 in 360°! | City of...,68,00:00:00,2018-12-31,31,12,2018
27423,2018-12-31,Council Directory | City of Los Angeles,65,00:00:00,2018-12-31,31,12,2018
27424,2018-12-31,City Council | City of Los Angeles,63,00:00:00,2018-12-31,31,12,2018

In [38]:
df3.nlargest(15,['pageviews'])

,date,pageTitle,pageviews,time,Date,day,month,year
19530,2018-02-20,City of Los Angeles |,7741,00:00:00,2018-02-20,20,02,2018
19705,2018-02-27,City of Los Angeles |,7102,00:00:00,2018-02-27,27,02,2018
19555,2018-02-21,City of Los Angeles |,7013,00:00:00,2018-02-21,21,02,2018
19730,2018-02-28,City of Los Angeles |,6981,00:00:00,2018-02-28,28,02,2018
19580,2018-02-22,City of Los Angeles |,6830,00:00:00,2018-02-22,22,02,2018
19680,2018-02-26,City of Los Angeles |,6769,00:00:00,2018-02-26,26,02,2018
19180,2018-02-06,City of Los Angeles |,6464,00:00:00,2018-02-06,06,02,2018
19255,2018-02-09,City of Los Angeles |,6343,00:00:00,2018-02-09,09,02,2018
19330,2018-02-12,City of Los Angeles |,6290,00:00:00,2018-02-12,12,02,2018
19205,2018-02-07,City of Los Angeles |,6270,00:00:00,2018-02-07,07,02,2018
18830,2018-01-23,City of Los Angeles |,6206,00:00:00,2018-01-23,23,01,2018
19531,2018-02-20,Find Jobs | City of Los Angeles,6127,00:00:00,2018-02-20,20,02,2018
18980,2018-01-29,City of Los Angeles |,6089,00:00:00,2018-01-29,29,01,2018
19155,2018-02-05,City of Los Angeles |,6082,00:00:00,2018-02-05,05,02,2018
19230,2018-02-08,City of Los Angeles |,6049,00:00:00,2018-02-08,08,02,2018

In [37]:
df4=df.loc[df['year'] =="2019"]
df4

,date,pageTitle,pageviews,time,Date,day,month,year
12840,2019-08-25,Current Job Openings | Page 3 | City of Los An...,217,00:00:00,2019-08-25,25,08,2019
13447,2019-08-25,Los Angeles Municipal Code (LAMC) 85.02 – Vehi...,157,00:00:00,2019-08-25,25,08,2019
13448,2019-08-25,Meet Your Government | City of Los Angeles,153,00:00:00,2019-08-25,25,08,2019
13449,2019-08-25,Map Of Districts | City of Los Angeles,135,00:00:00,2019-08-25,25,08,2019
13450,2019-08-25,Council Directory | City of Los Angeles,123,00:00:00,2019-08-25,25,08,2019
...,...,...,...,...,...,...,...,...
33345,2019-08-26,Tips for Visitors | City of Los Angeles,185,00:00:00,2019-08-26,26,08,2019
33346,2019-08-26,Los Angeles Municipal Code (LAMC) 85.02 – Vehi...,172,00:00:00,2019-08-26,26,08,2019
33347,2019-08-26,Planning and Zoning | City of Los Angeles,154,00:00:00,2019-08-26,26,08,2019
33348,2019-08-26,Council and Committee Meetings | City of Los A...,151,00:00:00,2019-08-26,26,08,2019
33349,2019-08-26,Housing Services | City of Los Angeles,147,00:00:00,2019-08-26,26,08,2019

In [39]:
df4.nlargest(15,['pageviews'])

,date,pageTitle,pageviews,time,Date,day,month,year
27475,2019-01-03,Download the ShakeAlertLA Earthquake Early War...,13387,00:00:00,2019-01-03,03,01,2019
27500,2019-01-04,Download the ShakeAlertLA Earthquake Early War...,6794,00:00:00,2019-01-04,04,01,2019
32052,2019-07-05,Download the ShakeAlertLA Earthquake Early War...,6586,00:00:00,2019-07-05,05,07,2019
32027,2019-07-04,Download the ShakeAlertLA Earthquake Early War...,6497,00:00:00,2019-07-04,04,07,2019
28850,2019-02-27,City of Los Angeles |,5135,00:00:00,2019-02-27,27,02,2019
28825,2019-02-26,City of Los Angeles |,4533,00:00:00,2019-02-26,26,02,2019
28875,2019-02-28,City of Los Angeles |,4528,00:00:00,2019-02-28,28,02,2019
32152,2019-07-09,City of Los Angeles |,4523,00:00:00,2019-07-09,09,07,2019
29350,2019-03-19,City of Los Angeles |,4435,00:00:00,2019-03-19,19,03,2019
28800,2019-02-25,City of Los Angeles |,4368,00:00:00,2019-02-25,25,02,2019
29325,2019-03-18,City of Los Angeles |,4332,00:00:00,2019-03-18,18,03,2019
33003,2019-08-12,City of Los Angeles |,4274,00:00:00,2019-08-12,12,08,2019
30601,2019-05-08,City of Los Angeles |,4214,00:00:00,2019-05-08,08,05,2019
30226,2019-04-23,City of Los Angeles |,4173,00:00:00,2019-04-23,23,04,2019
28675,2019-02-20,City of Los Angeles |,4171,00:00:00,2019-02-20,20,02,2019